"""Generated badge consumer contracts; no retained-game transaction or input.

Badge pixels, PNG identities and local resources are real generated bytes read
by the production helpers. Names, prices and page geometry are explicit test
predicates, not native OCR measurements. The Worker fixture has inert transport;
these tests stop at eligibility/authorization and invent no purchase outcome.
"""
from __future__ import annotations

import contextlib
import copy
import hashlib
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import Mock, patch

import cv2
import numpy as np
from PIL import Image
from PIL.PngImagePlugin import PngInfo

import currency_wars_runner as runner
import currency_wars_shop_reader as shop_reader
import currency_wars_visual_guards as visual_guards
import test_currency_wars_economy as economy_contracts


CARD = (400, 60, 244, 273)
NAME_BOUNDS = [415, 275, 580, 302]
COST_BOUNDS = [605, 287, 635, 322]


def generated_badge(hue=24):
    """Geometric book/star art drawn here, with no private game template."""
    gold = tuple(map(int, cv2.cvtColor(np.uint8([[[hue, 225, 245]]]), cv2.COLOR_HSV2RGB)[0, 0]))
    badge = np.full((51, 47, 3), 210, dtype=np.uint8)
    cv2.circle(badge, (23, 25), 21, (65, 65, 65), -1)
    cv2.circle(badge, (23, 25), 21, gold, 2)
    cv2.polylines(badge, [np.array([(12, 20), (23, 25), (34, 20), (34, 37),
                                  (23, 43), (12, 37), (12, 20)])], True, gold, 2)
    cv2.line(badge, (23, 25), (23, 43), gold, 2)
    cv2.fillPoly(badge, [np.array([(23, 9), (25, 13), (30, 14), (26, 17),
                                 (27, 21), (23, 19), (19, 21), (20, 17),
                                 (16, 14), (21, 13)])], gold)
    return badge


class BadgeConsumerTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix='currency-wars-badge-protocol-')
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.resources = self.root / 'generated-resources'
        self.resources.mkdir()
        template = self.resources / 'recommend_badge.png'
        Image.fromarray(generated_badge()).save(template, format='PNG')
        (self.resources / 'SOURCES.json').write_text(json.dumps({
            'schema': 'generated-badge-protocol-resource/v1',
            'provenance': 'Generated geometric art; no retained game template or OCR measurement.',
            'resources': [{'file': template.name, 'sha256': hashlib.sha256(template.read_bytes()).hexdigest()}],
        }), encoding='utf-8')
        (self.resources / 'names.json').write_text(json.dumps({'names': ['飞霄']}), encoding='utf-8')
        replacement = patch.object(shop_reader, 'RESOURCE_DIR', self.resources)
        replacement.start()
        self.addCleanup(replacement.stop)
        self.reader = shop_reader.ShopReader(self.resources)
        self.reader.engine = Mock(side_effect=AssertionError('Badge consumers must not invoke OCR'))
        self.reader._load()
        self.serial = 0

    def frame(self, *, hue=16, marker=0, cost=1, badge=True, base=None):
        rgb = np.full((1080, 1920, 3), 110, dtype=np.uint8) if base is None else base.copy()
        x, y, width, height = CARD
        cv2.rectangle(rgb, (x, y), (x + width - 1, y + height - 1), (180, 180, 180), 1)
        if badge:
            rgb[y + 9:y + 60, x + 11:x + 58] = generated_badge(hue)
        # These labels express the declared name/price protocol. No OCR is run.
        cv2.putText(rgb, 'FX', (NAME_BOUNDS[0] + 3, NAME_BOUNDS[3] - 4),
                    cv2.FONT_HERSHEY_SIMPLEX, .7, (250, 250, 250), 2)
        cv2.putText(rgb, str(cost), (COST_BOUNDS[0] + 3, COST_BOUNDS[3] - 5),
                    cv2.FONT_HERSHEY_SIMPLEX, .8, (250, 250, 250), 2)
        if base is None:
            cv2.putText(rgb, '66', (1640, 930), cv2.FONT_HERSHEY_SIMPLEX, .7, (250, 250, 250), 2)
        rgb[500:520, 50:80] = (20 + marker * 30, 70, 100)
        self.serial += 1
        path = self.root / ('generated-frame-' + str(self.serial) + '.png')
        Image.fromarray(rgb).save(path, format='PNG')
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        recommended, evidence = self.reader._recommended(rgb, CARD, snapshot_id=digest)
        slot = {
            'slot': 1, 'status': 'recognized' if type(recommended) is bool else 'unknown',
            'name': '飞霄', 'cost': cost, 'recommended': recommended,
            'bounds': list(CARD), 'position': [round(x + width / 2), round(y + height / 2)],
            'evidence': {
                'name': {'method': 'ocr', 'confidence': .99, 'bounds': list(NAME_BOUNDS)},
                'cost': {'method': 'digit_ocr', 'confidence': .99, 'ocr_bounds': list(COST_BOUNDS),
                         'raw_ocr': [{'raw': str(cost), 'confidence': .99}]},
                'recommended': evidence,
            },
            'fixture_origin': 'Name/cost/page are declared protocol predicates; badge is actually derived.',
        }
        native = {
            'schema': shop_reader.SCHEMA,
            'input': {'sha256': digest, 'size': [1920, 1080], 'format': 'PNG'},
            'page': {'reliable_open_shop': True, 'geometry': {'frame_scores': [.99] * 5, 'overlays': []}},
            'slots': [slot, *({'slot': number, 'status': 'empty'} for number in range(2, 6))],
        }
        observation = {
            'snapshot_id': digest, 'page': 'shop', 'fields': {'stage': '2-3', 'level': '7', 'deployed': '7/7'},
            'semantic': {'coins': {'value': 66, 'bounds': runner.GOLD_HUD,
                                   'currency_icon_gold_fraction': .8}},
            'rows': [], 'shop': native, 'fingerprint': '0' * 64, 'elapsed_ms': 0.,
        }
        return {'path': path, 'rgb': rgb, 'observation': observation}

    @staticmethod
    def action(cost=1):
        return {'type': 'buy_shop', 'slot': 1, 'name': '飞霄', 'cost': cost,
                'expected_page': 'shop', 'reason': 'Explicit generated current-gap protocol'}

    def stable_slot(self, original, actual, *, images=True):
        old, fresh = original['observation'], actual['observation']
        return shop_reader.stable_purchase_slot(old['shop'], fresh['shop'], 1,
            old['snapshot_id'], fresh['snapshot_id'],
            images=[original['rgb'], actual['rgb']] if images else None)

    def stable_plan(self, original, actual, *, action=None):
        old = original['observation']
        request = {'kind': 'shop_strategy', 'snapshot_id': old['snapshot_id'],
                   'observation': old, 'original_png': str(original['path'])}
        reply = {'snapshot_id': old['snapshot_id'], 'actions': [action or self.action()]}
        return visual_guards.stable_semantic_plan(reply, request, actual['observation'], actual['path'])

    def test_same_slot_rederives_gold_badge_from_both_pngs_without_ocr(self):
        for hue in (16, 24):
            with self.subTest(hue=hue):
                original, actual = self.frame(hue=hue), self.frame(hue=hue, marker=1)
                self.assertNotEqual(original['observation']['snapshot_id'], actual['observation']['snapshot_id'])
                for frame in (original, actual):
                    slot = frame['observation']['shop']['slots'][0]
                    self.assertIs(slot['recommended'], True)
                    self.assertEqual(slot['evidence']['recommended']['snapshot_id'], frame['observation']['snapshot_id'])
                    self.assertEqual(slot['evidence']['recommended']['card_bounds'], list(CARD))
                with patch.object(shop_reader.ShopReader, '_load',
                                  side_effect=AssertionError('Revalidation must not load all shop resources')):
                    self.assertIsNotNone(self.stable_slot(original, actual))
                    self.assertTrue(self.stable_plan(original, actual))
                self.assertIsNone(self.stable_slot(original, actual, images=False))
        original, actual = self.frame(badge=False), self.frame(badge=False, marker=1)
        self.assertIs(original['observation']['shop']['slots'][0]['recommended'], False)
        self.assertIsNotNone(self.stable_slot(original, actual))
        self.reader.engine.assert_not_called()

    def test_source_frame_slot_price_or_recommendation_changes_reject(self):
        original, source = self.frame(), self.frame(marker=1)
        mutations = {
            'shop_source_sha': lambda obs: obs['shop']['input'].update(sha256='0' * 64),
            'badge_source_sha': lambda obs: obs['shop']['slots'][0]['evidence']['recommended'].update(snapshot_id='0' * 64),
            'badge_roi_pixels': lambda obs: obs['shop']['slots'][0]['evidence']['recommended'].update(roi_rgb_sha256='0' * 64),
            'badge_resource_source': lambda obs: obs['shop']['slots'][0]['evidence']['recommended'].update(template_source={}),
            'badge_card_binding': lambda obs: obs['shop']['slots'][0]['evidence']['recommended'].update(card_bounds=[401, 60, 244, 273]),
            'different_slot': lambda obs: obs['shop']['slots'][0].update(slot=2),
            'recommendation_changed': lambda obs: obs['shop']['slots'][0].update(recommended=False),
            'recommendation_unknown': lambda obs: obs['shop']['slots'][0].update(recommended=None),
            'page_changed': lambda obs: obs.update(page='preparation'),
            'overlay': lambda obs: obs['shop']['page']['geometry'].update(overlays=[{'declared': 'occluded'}]),
        }
        self.assertTrue(self.stable_plan(original, source))
        for label, change in mutations.items():
            with self.subTest(change=label):
                actual = {**source, 'observation': copy.deepcopy(source['observation'])}
                change(actual['observation'])
                self.assertFalse(self.stable_plan(original, actual))
        with self.subTest(change='current_price'):
            actual = self.frame(marker=1, cost=2)
            self.assertIs(actual['observation']['shop']['slots'][0]['recommended'], True)
            self.assertFalse(self.stable_plan(original, actual))
            self.assertFalse(self.stable_plan(original, actual, action=self.action(cost=2)))
        with self.subTest(change='current_png_bytes'):
            payload = source['path'].read_bytes()
            try:
                source['path'].write_bytes(self.frame(marker=2)['path'].read_bytes())
                self.assertFalse(self.stable_plan(original, source))
            finally:
                source['path'].write_bytes(payload)
        self.reader.engine.assert_not_called()

    def test_unknown_or_changed_local_resources_cannot_qualify(self):
        original, actual = self.frame(), self.frame(marker=1)
        unknown, evidence = self.reader._recommended(actual['rgb'], CARD)
        self.assertIsNone(unknown)
        unread = {**actual, 'observation': copy.deepcopy(actual['observation'])}
        slot = unread['observation']['shop']['slots'][0]
        slot.update(recommended=unknown)
        slot['evidence']['recommended'] = evidence
        self.assertFalse(self.stable_plan(original, unread))
        # Badges are required only for this animation exception. Native gap
        # purchase eligibility still uses its original name/cost/source guards.
        self.assertIsNotNone(shop_reader.purchase_slot(unread['observation']['shop'], 1,
                                                      unread['observation']['snapshot_id']))
        manifest = self.resources / 'SOURCES.json'
        manifest_bytes = manifest.read_bytes()
        with self.subTest(change='manifest_identity'):
            try:
                manifest.write_bytes(manifest_bytes + b'\n')
                self.assertFalse(self.stable_plan(original, actual))
            finally:
                manifest.write_bytes(manifest_bytes)
        template = self.resources / 'recommend_badge.png'
        template_bytes = template.read_bytes()
        with self.subTest(change='template_container_identity'):
            try:
                metadata = PngInfo()
                metadata.add_text('fixture', 'Different generated container; identical decoded template pixels')
                Image.fromarray(generated_badge()).save(template, format='PNG', pnginfo=metadata)
                self.assertNotEqual(template.read_bytes(), template_bytes)
                with Image.open(template) as opened:
                    self.assertTrue(np.array_equal(np.array(opened.convert('RGB')), generated_badge()))
                self.assertFalse(self.stable_plan(original, actual))
            finally:
                template.write_bytes(template_bytes)
        with self.subTest(change='template_missing'):
            try:
                template.unlink()
                self.assertFalse(self.stable_plan(original, actual))
                self.reader._load()
                result, unused = self.reader._recommended(actual['rgb'], CARD,
                                                         snapshot_id=actual['observation']['snapshot_id'])
                self.assertIsNone(result)
            finally:
                template.write_bytes(template_bytes)
                self.reader._load()
        self.reader.engine.assert_not_called()

    @contextlib.contextmanager
    def worker(self):
        with economy_contracts.EconomyTests().worker() as (worker, record, control, rendered):
            # Keep the fixture's numeric ROIs intact, and route a new immutable
            # generated capture through the real Entry/Worker observation path.
            frame = self.frame(base=np.array(rendered[0][0]))
            frame['observation']['rows'] = copy.deepcopy(worker.last_observation['rows'])
            control.frame = frame['path'].read_bytes()

            def read(path, force=False, *, scope='full'):
                digest = hashlib.sha256(Path(path).read_bytes()).hexdigest()
                self.assertEqual(digest, frame['observation']['snapshot_id'])
                return copy.deepcopy(frame['observation'])

            with patch.object(worker.perception, 'read', side_effect=read), patch.object(shop_reader, 'RESOURCE_DIR', self.resources):
                worker.observe()
                worker.ask(worker.last_observation, 'shop_strategy', 'Generated badge policy boundary; no purchase execution')
                request = worker.state['decision_request']
                record['proof'].update(snapshot_id=request['snapshot_id'], evidence_file=request['evidence_file'],
                                       resume_epoch=worker.epoch())
                record['value'].update(
                    targets=[{'name': '飞霄', 'copies': 1, 'reason': 'Declared current gap', 'critical': False}],
                    budget={'purchase': 1, 'refresh': 0, 'experience': 0})
                yield worker, record, control

    def test_badge_eligibility_preserves_current_worker_policy_guards(self):
        for condition in ('allowed', 'no_target', 'no_budget', 'guide_missing', 'mode_mismatch', 'epoch_changed', 'pending'):
            with self.subTest(condition=condition), self.worker() as (worker, record, control):
                actual = worker.last_observation
                self.assertIs(actual['shop']['slots'][0]['recommended'], True)
                published = len(control.published)
                if condition == 'no_target':
                    record['value']['targets'] = []
                elif condition == 'no_budget':
                    record['value']['budget']['purchase'] = 0
                elif condition == 'mode_mismatch':
                    record['value']['mode'] = '超频博弈'
                if condition == 'mode_mismatch':
                    with self.assertRaisesRegex(ValueError, '模式'):
                        worker.accept_economy_plan(record)
                    self.assertEqual(len(control.published), published)
                    continue
                worker.accept_economy_plan(record)
                ledger = worker.economy_ledger('2-3')
                pending = None
                if condition == 'guide_missing':
                    worker.preparation_reviews.pop('startup_guide')
                elif condition == 'epoch_changed':
                    worker.epoch = lambda: 'different-protocol-epoch'
                elif condition == 'pending':
                    # An explicit unknown pending precondition; not a claimed
                    # receipt, successful action, or reconstructed game chain.
                    pending = {'kind': 'purchase', 'request_id': 'declared-original-pending', 'cost': 1}
                    ledger['pending'] = copy.deepcopy(pending)
                if condition == 'allowed':
                    worker.require_strategy_context(actual)
                    self.assertEqual(worker.require_economic_action(self.action(), actual)['cost'], 1)
                elif condition == 'guide_missing':
                    with self.assertRaises(ValueError):
                        worker.require_strategy_context(actual)
                else:
                    with self.assertRaises(ValueError):
                        worker.require_economic_action(self.action(), actual)
                self.assertEqual(len(control.published), published)
                self.assertEqual(ledger['pending'], pending)
                self.assertEqual(ledger['spent'], {'purchase': 0, 'refresh': 0, 'experience': 0})
                self.assertEqual(control.action_index, 0)
        self.reader.engine.assert_not_called()


if __name__ == '__main__':
    unittest.main()
